In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
b = np.array(a)

In [4]:
a = np.array(b, dtype = float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
a.dtype

dtype('float64')

In [6]:
a[3]

3.0

In [7]:
a.ndim

1

In [8]:
a.shape

(10,)

### 2D array

In [9]:
b = np.array([
    [i for i in range(10)],
     [i for i in range(10,20)],
     [i for i in range(20,30)]
])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [10]:
b.shape

(3, 10)

In [11]:
b.size

30

In [12]:
b[2,9]

29

In [13]:
b[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [14]:
c = b[1:,5:]
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [15]:
c = b[1:,5:].copy()
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

   ### Data types

In [16]:
b = np.array([1.,2.,3.], dtype = np.float32)
b

array([1., 2., 3.], dtype=float32)

In [17]:
a = np.array([i for i in range(5)])
a

array([0, 1, 2, 3, 4])

In [18]:
b = np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

### сложение векторов

In [19]:
c = a + b
c

array([ 5,  7,  9, 11, 13])

### или np.add(a,b)

In [20]:
e = np.add(a,b)
e

array([ 5,  7,  9, 11, 13])

### вычитание векторов

In [21]:
d = a - b
d

array([-5, -5, -5, -5, -5])

### или np.subtract(a,b)

In [22]:
e = np.subtract(a,b)
e

array([-5, -5, -5, -5, -5])

In [23]:
a.shape == b.shape

True

In [24]:
a + 2

array([2, 3, 4, 5, 6])

In [25]:
a

array([0, 1, 2, 3, 4])

In [26]:
a * 2

array([0, 2, 4, 6, 8])

In [27]:
[1,2,3] * 2

[1, 2, 3, 1, 2, 3]

### Умножение

In [28]:
# Вариант 1
a.dot(-10)

array([  0, -10, -20, -30, -40])

In [29]:
# Вариант 2
np.dot(-10,a)

array([  0, -10, -20, -30, -40])

In [30]:
# Вариант 3
np.multiply(-10,a)

array([  0, -10, -20, -30, -40])

### Скалярное произведение векторов

In [31]:
a = np.array([5,4,3])
b = np.array([2,6,7])

In [32]:
c = a[0]*b[0]+a[1]*b[1]+a[2]*b[2]
c

55

In [33]:
a @ b

55

In [34]:
np.dot(a,b)

55

## Операции над матрицами

In [35]:
A = np.array([[0,1],
             [2,3],
             [4,5]])

In [36]:
B = np.array([[6,7],
             [8,9],
             [10,11]])

In [37]:
A.shape

(3, 2)

In [38]:
B.shape

(3, 2)

### Сложение матриц

In [39]:
C = np.add(A,B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Умножение на скаляр

In [40]:
X = np.array([[0,1],[2,3]])

In [41]:
X * 3

array([[0, 3],
       [6, 9]])

## Умножения матриц

In [42]:
X1 = np.array([[0,1],
             [2,3],
             [4,5]])

In [43]:
X2 = np.array([[7,8,9,10],
             [11,12,13,14]])

In [44]:
X1.shape

(3, 2)

In [45]:
X2.shape

(2, 4)

In [46]:
X1.shape[1] == X2.shape[0]

True

In [47]:
X1.shape,X2.shape

((3, 2), (2, 4))

In [48]:
Z = np.dot(X1,X2)
Z

array([[ 11,  12,  13,  14],
       [ 47,  52,  57,  62],
       [ 83,  92, 101, 110]])

In [49]:
Z.shape

(3, 4)

In [50]:
X1[0,0]*X2[0,0]+X1[0,1]*X2[1,0]

11

## Модуль матрицы numpy.linalg: возведение матрицы в квадрат

In [51]:
A = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [52]:
A_square = np.linalg.matrix_power(A,2)

In [53]:
A_square

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## Создание единичной матрицы

In [54]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Умножение матрицы на единичную матрицу

In [55]:
A = np.array([[1,2],
             [3,4],
             [5,6]])

#### Случай 1

In [56]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [57]:
np.dot(A,I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Транспонирование матрицы

In [58]:
A = np.array([[11,13],
             [16,9],
             [8,15]])

In [59]:
At = np.transpose(A)
At

array([[11, 16,  8],
       [13,  9, 15]])

### Альтернативный вариант

In [60]:
As = A.T
As

array([[11, 16,  8],
       [13,  9, 15]])

### Расмотрим X и Y

In [61]:
X = np.array([[1,2],
            [3,4],
            [5,6]])

In [62]:
Y = np.array([[0,1],
              [3,4],
             [6,7],
             [2,5]])

In [63]:
Yt = np.transpose(Y)
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [64]:
np.dot(X,Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

### Вычисление определителя и ранга матрицы

### Пример

In [65]:
A = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])

In [66]:
# определитель
np.linalg.det(A)

0.0

In [67]:
np.linalg.matrix_rank(A)

2

### Вычисление обратной матрицы

In [68]:
B = np.array([[7,4,5],
             [8,3,2],
             [6,10,12]])

In [69]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [70]:
B_inv_2 = np.linalg.inv(B_inv)
B_inv_2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

## Автоматическое создание массивов

In [71]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
a = np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Дробный шаг

In [76]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### np.linspace() - то же самое но правая граница будет включена. Третим элементом нужное число элементовю

In [77]:
np.linspace(0,9.9,100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### np.logspace -  похоже на lin, но указываем степень 10

In [78]:
np.logspace(2,4,4)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

### Генерация случайных чисел
### numpy.random.sample() случайное число от (0.0,1.0)

In [79]:
np.random.sample()

0.8958766408347222

In [80]:
np.random.sample(3)

array([0.50542775, 0.48706703, 0.34622583])

In [81]:
np.random.sample((2,3))

array([[0.96466099, 0.06932742, 0.67112111],
       [0.76005575, 0.49927024, 0.7368388 ]])

In [82]:
# np.random.sample((64,48,3))

### numpy.random.randn - случайное число с нормальным распраделением
### (среднее значение = 0, среднеквадратичное отклонение = 1)

In [83]:
np.random.randn(10)

array([-1.45653856, -0.58885937,  1.73670118,  0.15145132, -1.07414944,
        0.52111593,  1.2365181 ,  0.62837469, -0.23734948, -1.67679389])

In [84]:
np.random.randn(3,4)

array([[-0.99891014, -1.40114323, -0.0561631 ,  0.10576868],
       [ 0.07408703,  1.80873772, -1.92734172, -0.21872696],
       [-1.58869082,  1.79967721,  1.46795979,  0.5096822 ]])

### numpy.random.randint -массив из целых чисел
### случайные числа от до и сколько штук

In [85]:
np.random.randint(0,100,10)

array([55,  9, 50, 84, 14, 27, 10, 30, 34, 89])

In [86]:
np.random.randint(0,100,(3,5))

array([[87, 17, 70, 77, 10],
       [21, 29, 33, 66, 21],
       [87, 43, 82, 56, 32]])

### numpy.random.choice - случайный выбор элемента из массива

In [87]:
b = np.array([i for i in range(10)])
np.random.choice(b)

6

In [88]:
np.random.choice(b,3)

array([9, 6, 5])

### numpy.random.seed - инициализация генератора случайных чисел
### может использоваться для последующей воспроизводимости

In [89]:
np.random.seed(42)

In [90]:
np.random.randint(0,10,3)

array([6, 3, 7])

## Изменения формы массива

In [91]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [92]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
# можно указать только число строк
np.reshape(a,(4,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
np.reshape(a,(-1,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
# inplace
a.resize(3,4)

In [97]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Соединение массивов

In [99]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

### Соединение строк вертикально

In [101]:
v = np.vstack((a,b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
# Вариант 2
np.concatenate((a,b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Соединение строк горизонтально

In [103]:
h = np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [104]:
np.concatenate((a,b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

### Соединение в глубину

In [105]:
d = np.dstack((a,b))
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

## Выбор данных

In [108]:
a = np.random.randint(0,20,10)
a

array([ 1,  0, 11, 11, 16,  9, 15, 14, 14, 18])

In [109]:
a[a>10]

array([11, 11, 16, 15, 14, 14, 18])

In [111]:
a[(a>7)&(a%2==0)]

array([16, 14, 14, 18])

In [114]:
a[(a<7) | (a==15)]

array([ 1,  0, 15])

## numpy.where

In [116]:
# Вариант 1
# Возвращает индексы элементов по условию
np.where(a>10)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

### Вариант 2

In [117]:
a = [1,2,3]
b = [4,5,6]

In [118]:
np.where([True,False,True],a,b)

array([1, 5, 3])

## Сортировка

In [119]:
a = np.random.randint(1,11,(3,4))
a

array([[7, 4, 9, 3],
       [5, 3, 7, 5],
       [9, 7, 2, 4]])

In [122]:
a[[1,0,2],:]

array([[5, 3, 7, 5],
       [7, 4, 9, 3],
       [9, 7, 2, 4]])

In [124]:
# получаем индексы
a.argsort(axis=0)

array([[1, 1, 2, 0],
       [0, 0, 1, 2],
       [2, 2, 0, 1]], dtype=int64)

In [125]:
a[:,0].argsort()

array([1, 0, 2], dtype=int64)

In [126]:
a[a[:,0].argsort(),:]

array([[5, 3, 7, 5],
       [7, 4, 9, 3],
       [9, 7, 2, 4]])

## Случайное перемешивание

In [127]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
# inplace на месте
np.random.shuffle(a)

In [129]:
a

array([6, 3, 2, 5, 4, 7, 0, 9, 1, 8])

## Двумерные массивы

In [131]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [132]:
# inplace на месте
np.random.shuffle(a)

In [133]:
a

array([[ 9, 10, 11],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [ 6,  7,  8]])

## Математические действия с массивами

In [134]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
# Логарифм по основания E
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [137]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [139]:
# сумма всех элементов
a.sum()

21

In [140]:
# axis=0 по столбцу
a.sum(axis=0)

array([5, 7, 9])

In [142]:
a.sum(axis=1)

array([ 6, 15])

In [143]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

## Поэлементное умножениу (не матричное) 

In [144]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
b = np.arange(12).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
a * b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

### Broadcastig (на примере сложения)

In [153]:
# совпадают число столбцов
a = np.random.randint(10,20,(3,2))
a

array([[12, 10],
       [13, 11],
       [17, 13]])

In [155]:
b = np.array([1,2])
b

array([1, 2])

In [156]:
a + b

array([[13, 12],
       [14, 13],
       [18, 15]])

In [157]:
# совпадают число строк
a = np.random.randint(10,30,(3,4))
a

array([[11, 15, 19, 13],
       [27, 21, 11, 19],
       [13, 23, 25, 24]])

In [163]:
b = np.random.randint(20,50,(3,1))
b

array([[31],
       [27],
       [43]])

In [164]:
a + b

array([[42, 46, 50, 44],
       [54, 48, 38, 46],
       [56, 66, 68, 67]])

## Статистические функции

In [165]:
a = np.random.randint(10,30,(3,4))
a

array([[20, 28, 26, 17],
       [12, 12, 10, 14],
       [19, 16, 18, 16]])

In [166]:
a.min()

10

In [170]:
a.min(axis=0)

array([12, 12, 10, 14])

In [168]:
a.max()

28

In [171]:
a.max(axis=1)

array([28, 14, 19])

In [172]:
a.mean(axis=0)

array([17.        , 18.66666667, 18.        , 15.66666667])

In [173]:
a.std(axis=1)

array([4.43705984, 1.41421356, 1.29903811])

## Запись и чтение массива

In [174]:
np.save('a.npy',a)

In [175]:
b = np.load('a.npy')

In [176]:
b

array([[20, 28, 26, 17],
       [12, 12, 10, 14],
       [19, 16, 18, 16]])